name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install cmake

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
